#
# See https://docs.microsoft.com/azure/devops/pipelines/yaml-schema for details
#

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - prkrishn/build

stages:
- stage: build
  displayName: Build
  jobs:
  - job: "UpdateMono"
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "prkrishn+bot@hotmail.com"
          git config --global user.name "Pranav K (bot)"
          git commit -am --allow-empty "Empty test"
          git checkout -B prkrishn/update-mono-build
          git push origin +prkrishn/update-mono-build
       


