#
# See https://docs.microsoft.com/azure/devops/pipelines/yaml-schema for details
#

# CI and PR triggers

stages:
- stage: build
  displayName: Build
  jobs:
  - job: "UpdateMono"
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $scriptPath = Join-Path $(Agent.TempDirectory) -ChildPath UpgradeMono.ps1
          Copy-Item -Force ./UpgradeMono.ps1 $scriptPath
          git fetch https://github.com/dotnet/Blazor master:upstream-master
          git checkout upstream-master -B update-mono-build --force
          git config --global user.email "prkrishn+bot@hotmail.com"
          git config --global user.name "Pranav K (bot)"

          & "$scriptPath" -repoRoot $(System.DefaultWorkingDirectory) -commitChanges -tempDir $(Agent.TempDirectory)
          git push https://pranavkm:$(_PAT)@github.com/pranavkm/blazor +update-mono-build



