#
# See https://docs.microsoft.com/azure/devops/pipelines/yaml-schema for details
#

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - prkrishn/build

stages:
- stage: build
  displayName: Build
  jobs:
  - job: "UpdateMono"
    steps:
    - task: PowerShell@2
    inputs:
        filePath: 'UpgradeMono.ps1'
        arguments: '-commitChanges'
    
        


